#pragma once
#ifndef VERSION_H
#define VERSION_H
#define VER_COMPANYNAME_STR "Hollis Technology Solutions"
#define VER_LEGALCOPYRIGHT_STR "(C) " VER_COMPANYNAME_STR
#define VER_PRODUCTNAME "HTS Build Samples"
#define VER_INTERNAL_FILEDESCRIPTION_STR VER_PRODUCTNAME
#define VER_INTERNALNAME_STR VER_PRODUCTNAME
#endif
