name: "Debug Build"

on: [push,workflow_dispatch]

env:

  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Debug
  BUILD_PLATFORM: x64,arm64
  TOOLSET: VS2022
  ARCHIVE_PREFIX: debug-build

jobs:
  build:
    runs-on: [windows-latest]
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with: 
        submodules: 'true'
        fetch-depth: 0 # required for generating version number
        
    - name: Setup NuGet
      run: nuget restore .\packages.config -PackagesDirectory .\packages\ 
      
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: >
        .\BuildTools\build.ps1 -toolset ${{env.TOOLSET}} 
        -configurations ${{env.BUILD_CONFIGURATION}} 
        -platforms ${{env.BUILD_PLATFORM}}

    - name: Archive logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.ARCHIVE_PREFIX}}-logs
        path: logs/**/*.log

    - name: Archive Bin
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.ARCHIVE_PREFIX}}-bin
        path: bin/**/*.*
